version: "3.8"

services:
  traefik:
    image: traefik:v2.10
    command:
      - --providers.docker=true
      - --providers.file.filename=/etc/traefik/dynamic.yml
      - --entrypoints.web.address=:80
      - --log.level=INFO
    ports:
      - "80:80"
      - "8080:8080" # Traefik dashboard (optional)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/dynamic.yml:/etc/traefik/dynamic.yml:ro
    networks:
      - web

  frontend:
    build: ./frontend
    # ports:
    # - "8081:80"
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.front.rule=Host(`localhost`) && PathPrefix(`/`)"
    - "traefik.http.routers.front.entrypoints=web"
    - "traefik.http.routers.front.priority=1"
    - "traefik.http.services.front.loadbalancer.server.port=80"
    depends_on:
      - middleware
    networks:
      - web

  middleware:
    build: ./middleware
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - NODE_ENV=development
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`localhost`) && PathPrefix(`/api`)"
      - "traefik.http.routers.api.entrypoints=web"
      - "traefik.http.routers.api.priority=20"
      - "traefik.http.routers.api.middlewares=strip-api@docker"
      - "traefik.http.services.api.loadbalancer.server.port=3000"
      - "traefik.http.middlewares.strip-api.stripprefix.prefixes=/api"
    depends_on:
      - redis
    networks:
      - web

  redis:
    image: redis:7
    labels:
      - "traefik.enable=false"
    command: ["redis-server", "--save", "60", "1"]
    networks:
      - web

  loki:
    image: grafana/loki:2.8.2
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - web

  promtail:
    image: grafana/promtail:2.8.2
    labels:
      - "traefik.enable=false"
    volumes:
      - /var/log:/var/log:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ./promtail/promtail-config.yml:/etc/promtail/promtail-config.yml:ro
    command: -config.file=/etc/promtail/promtail-config.yml
    networks:
      - web

  grafana:
    image: grafana/grafana:10.2.1
    labels:
      - "traefik.enable=false"
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - web
    depends_on:
      - loki

networks:
  web:
    driver: bridge